Repository Linuxbrew/brew, pull requests merged in 2018-04, with the labels that each got.

#671 Merge 1.5.14
  Library/Homebrew/cask/lib/hbc/cask_loader.rb
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/cmd/doctor.rb
  Library/Homebrew/cmd/help.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/leaves.rb
  Library/Homebrew/cmd/switch.rb
  Library/Homebrew/cmd/tap.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/extend/ENV/std.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/extend/os/mac/system_config.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/language/python_virtualenv_constants.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/system_config.rb
  Library/Homebrew/tap.rb
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/cask/audit_spec.rb
  Library/Homebrew/test/cli_parser_spec.rb
  Library/Homebrew/test/cmd/switch_spec.rb
  Library/Homebrew/test/dev-cmd/tap_spec.rb
  Library/Homebrew/test/diagnostic_spec.rb
  Library/Homebrew/test/os/mac/diagnostic_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  completions/bash/brew
  completions/zsh/_brew
  docs/Formula-Cookbook.md
  docs/How-To-Open-a-Homebrew-Pull-Request.md
  docs/How-to-Create-and-Maintain-a-Tap.md
  docs/Interesting-Taps-and-Forks.md
  docs/Manpage.md
  docs/Troubleshooting.md
  manpages/brew.1
Labels: merge

#672 Dockerfile: Remove ~/.cache
  Dockerfile
Labels: enhancement

#673 Dockerfile: Tap homebrew/core
  Dockerfile
Labels: enhancement

#682 Clean up cross-platform diagnostic
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/extend/os/mac/diagnostic.rb
  Library/Homebrew/test/diagnostic_spec.rb
  Library/Homebrew/test/os/mac/diagnostic_spec.rb
Labels: enhancement

#685 bottle: Output root_url when it's not the default [Linux]
  Library/Homebrew/dev-cmd/bottle.rb
Labels: enhancement, in progress

#689 Merge 1.6.1
  Library/Homebrew/cask/lib/hbc/cli/search.rb
  Library/Homebrew/cli_parser.rb
  Library/Homebrew/cmd/missing.rb
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/extend/string.rb
  Library/Homebrew/compat/os/mac.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/bottle.rb
  Library/Homebrew/dev-cmd/mirror.rb
  Library/Homebrew/dev-cmd/pull.rb
  Library/Homebrew/dev-cmd/release-notes.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/dev-cmd/update-test.rb
  Library/Homebrew/keg_relocate.rb
  Library/Homebrew/test/cli_parser_spec.rb
  Library/Homebrew/test/cmd/missing_spec.rb
  docs/Analytics.md
  docs/Manpage.md
  manpages/brew.1
Labels: in progress
