Repository Linuxbrew/brew, pull requests merged in 2018-03, with the labels that each got.

#629 DependencyCollector: Add java_dep_if_needed [Linux]
  Library/Homebrew/dependency_collector.rb
  Library/Homebrew/extend/os/dependency_collector.rb
  Library/Homebrew/extend/os/linux/dependency_collector.rb
Labels: enhancement

#630 Merge tag Homebrew/1.5.6 into Linuxbrew/master
  .travis.yml
  Library/Homebrew/brew.sh
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/dev-cmd/irb.rb
  Library/Homebrew/dev-cmd/prof.rb
  Library/Homebrew/dev-cmd/ruby.rb
  Library/Homebrew/dev-cmd/tap-new.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/language/python.rb
  Library/Homebrew/manpages/brew.1.md.erb
  Library/Homebrew/test/dev-cmd/ruby_spec.rb
  docs/Manpage.md
  manpages/brew.1
Labels: merge

#632 zip_dep_if_needed: Needs unzip not zip [Linux]
  Library/Homebrew/dependency_collector.rb
  Library/Homebrew/test/os/linux/dependency_collector_spec.rb
Labels: bug

#631 Merge 1.5.7
  Library/Homebrew/extend/ENV.rb
  Library/Homebrew/migrator.rb
  Library/Homebrew/test/ENV_spec.rb
  docs/Acceptable-Formulae.md
Labels: merge

#634 check_undeclared_deps: Fix for taps
  Library/Homebrew/linkage_checker.rb
Labels: bug

#633 Merge 1.5.8
  Library/Homebrew/migrator.rb
Labels: merge

#636 homebrew_extra_paths: Do not add python to PATH [Linux]
  Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Labels: bug

#647 Adding link to `features` section
  README.md
Labels: enhancement

#649 support for Android linker
  Library/Homebrew/cmd/install.rb
Labels: enhancement

#651 Merge 1.5.9
  Library/Homebrew/cask/lib/hbc/system_command.rb
  Library/Homebrew/caveats.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/info.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/compat/dependency_collector.rb
  Library/Homebrew/compat/requirements.rb
  Library/Homebrew/compat/requirements/language_module_requirement.rb
  Library/Homebrew/dependable.rb
  Library/Homebrew/dependency.rb
  Library/Homebrew/dev-cmd/test.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/exceptions.rb
  Library/Homebrew/extend/ENV/super.rb
  Library/Homebrew/formula.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/language/python.rb
  Library/Homebrew/migrator.rb
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/rubocops.rb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/caveats_spec.rb
  Library/Homebrew/test/cmd/migrate_spec.rb
  Library/Homebrew/test/language_module_requirement_spec.rb
  Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
  Library/Homebrew/utils.rb
  bin/brew
  docs/Gems,-Eggs-and-Perl-Modules.md
  docs/Homebrew-and-Python.md
  docs/Manpage.md
  docs/Python-for-Formula-Authors.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: merge

#655 OS::Mac::CLT.installed?: Add module_function [Linux]
  Library/Homebrew/os/linux.rb
Labels: bug

#656 Merge 1.5.10
  Library/.rubocop.yml
  Library/Homebrew/.rubocop.yml
  Library/Homebrew/cask/lib/hbc/cask_loader.rb
  Library/Homebrew/cmd/gist-logs.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/reinstall.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/diagnostic.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/os/linux/system_config.rb
  Library/Homebrew/formula_versions.rb
  Library/Homebrew/language/python.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/sandbox.rb
  Library/Homebrew/tab.rb
  Library/Homebrew/test/Gemfile.lock
  Library/Homebrew/test/cmd/search_remote_tap_spec.rb
  Library/Homebrew/test/download_strategies_spec.rb
  Library/Homebrew/test/support/lib/config.rb
  Library/Homebrew/test/utils/analytics_spec.rb
  Library/Homebrew/utils/analytics.rb
  Library/Homebrew/utils/bottles.rb
  Library/Homebrew/utils/git.rb
  Library/Homebrew/utils/github.rb
  docs/Homebrew-and-Python.md
Labels: merge

#659 Merge 1.5.11
  Library/Homebrew/brew.sh
  Library/Homebrew/build.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/deps.rb
  Library/Homebrew/cmd/help.rb
  Library/Homebrew/cmd/install.rb
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/cmd/uses.rb
  Library/Homebrew/cmd/vendor-install.sh
  Library/Homebrew/compat.rb
  Library/Homebrew/compat/dependable.rb
  Library/Homebrew/compat/dependency_collector.rb
  Library/Homebrew/constants.rb
  Library/Homebrew/dependable.rb
  Library/Homebrew/dependency.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/create.rb
  Library/Homebrew/dev-cmd/man.rb
  Library/Homebrew/extend/ARGV.rb
  Library/Homebrew/formula_installer.rb
  Library/Homebrew/keg.rb
  Library/Homebrew/manpages/brew.1.md.erb
  Library/Homebrew/rubocops/dependency_order_cop.rb
  Library/Homebrew/rubocops/extend/formula_cop.rb
  Library/Homebrew/shims/scm/git
  Library/Homebrew/shims/super/pod2man
  Library/Homebrew/tap.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/cmd/pin_spec.rb
  Library/Homebrew/test/dependency_expansion_spec.rb
  Library/Homebrew/test/dependency_spec.rb
  Library/Homebrew/test/utils/git_spec.rb
  Library/Homebrew/test/utils/svn_spec.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/git.rb
  Library/Homebrew/utils/lock.sh
  Library/Homebrew/utils/ruby.sh
  Library/Homebrew/utils/svn.rb
  docs/Formula-Cookbook.md
  docs/Manpage.md
  manpages/brew.1
Labels: merge

#660 Revert "Don't use Linuxbrew/homebrew-core (yet, at least)."
  Library/Homebrew/cmd/update.sh
  Library/Homebrew/tap.rb
Labels: bug

#666 Add arm64 link loader
  Library/Homebrew/cmd/install.rb
Labels: enhancement

#668 bottle: Add option --or-later [Linux]
  Library/Homebrew/dev-cmd/bottle.rb
Labels: enhancement
