Repository Linuxbrew/brew, pull requests merged in 2018-08, with the labels that each got.

#775 Revert "Dockerfile: install unzip and subversion too"
  Dockerfile
Labels: enhancement

#778 Fix Bottle::Filename.new for taps
  Library/Homebrew/software_spec.rb
Labels: bug

#779 update-report: Work around an unusual error
  Library/Homebrew/cmd/update-report.rb
Labels: bug

#782 superenv: Use 02 optimization flag for Linux builds
  Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Labels: enhancement

#794 Remove cmd/patchelf.rb [Linux]
  Library/Homebrew/cmd/patchelf.rb
Labels: enhancement

#791 Remove OS::NAME [Linux]
  Library/Homebrew/os.rb
Labels: enhancement

#797 formula_installer: Use bottle_dependencies [Linux]
  Library/Homebrew/formula_installer.rb
Labels: bug

#805 README.md: Use https
  README.md
Labels: enhancement

#807 test/cask/cli/install: Revert [Linux]
  Library/Homebrew/test/cask/cli/install_spec.rb
Labels: enhancement

#808 Remove unused LINUX_TESTBALL_SHA256 [Linux]
  Library/Homebrew/test/support/lib/config.rb
Labels: enhancement

#809 Revert "system_command_spec.rb: require system_command"
  Library/Homebrew/test/system_command_spec.rb
Labels: enhancement

#810 Revert "analytics.sh: Fix missing git for Linuxbrew"
  Library/Homebrew/utils/analytics.sh
Labels: enhancement

#806 Revert XcodeRequirement [Linux]
  Library/Homebrew/requirements/xcode_requirement.rb
Labels: enhancement

#813 Update man files for CI errors
  docs/Manpage.md
  manpages/brew.1
Labels: bug

#817 Merge tag Homebrew/1.7.2 into Linuxbrew/master
  CONTRIBUTING.md
  Library/Homebrew/brew.rb
  Library/Homebrew/brew.sh
  Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb
  Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
  Library/Homebrew/cask/lib/hbc/cache.rb
  Library/Homebrew/cask/lib/hbc/cli.rb
  Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
  Library/Homebrew/cask/lib/hbc/cli/doctor.rb
  Library/Homebrew/cask/lib/hbc/installer.rb
  Library/Homebrew/cleanup.rb
  Library/Homebrew/cmd/cleanup.rb
  Library/Homebrew/cmd/update-report.rb
  Library/Homebrew/cmd/upgrade.rb
  Library/Homebrew/compat/hbc.rb
  Library/Homebrew/compat/hbc/cli/cleanup.rb
  Library/Homebrew/compat/hbc/cli/search.rb
  Library/Homebrew/dev-cmd/audit.rb
  Library/Homebrew/dev-cmd/tests.rb
  Library/Homebrew/download_strategy.rb
  Library/Homebrew/extend/os/formula_cellar_checks.rb
  Library/Homebrew/extend/os/formula_support.rb
  Library/Homebrew/extend/os/linux/formula_cellar_checks.rb
  Library/Homebrew/extend/os/linux/software_spec.rb
  Library/Homebrew/extend/os/mac/formula_support.rb
  Library/Homebrew/extend/os/software_spec.rb
  Library/Homebrew/formula_cellar_checks.rb
  Library/Homebrew/formula_support.rb
  Library/Homebrew/manpages/brew-cask.1.md
  Library/Homebrew/manpages/brew.1.md.erb
  Library/Homebrew/os/mac/pkgconfig/10.14/sqlite3.pc
  Library/Homebrew/os/mac/xcode.rb
  Library/Homebrew/rubocops/class_cop.rb
  Library/Homebrew/rubocops/conflicts_cop.rb
  Library/Homebrew/software_spec.rb
  Library/Homebrew/test/cask/cli/cleanup_spec.rb
  Library/Homebrew/test/cleanup_spec.rb
  Library/Homebrew/test/rubocops/class_cop_spec.rb
  Library/Homebrew/test/spec_helper.rb
  Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
  Library/Homebrew/test/unpack_strategy/subversion_spec.rb
  Library/Homebrew/test/utils_spec.rb
  Library/Homebrew/unpack_strategy/directory.rb
  Library/Homebrew/utils.rb
  Library/Homebrew/utils/github.rb
  completions/bash/brew
  completions/zsh/_brew_cask
  docs/Analytics.md
  docs/Gemfile.lock
  docs/Manpage.md
  manpages/brew-cask.1
  manpages/brew.1
Labels: merge

#815 Use Coretap.instance.slug when reporting brew version
  Library/Homebrew/cmd/--version.rb
Labels: enhancement

#819 update-report: Please donate to Linuxbrew and Homebrew
  Library/Homebrew/cmd/update-report.rb
Labels: enhancement

#822 manpage: update from latest homebrew-bundle docs.
  docs/Manpage.md
  manpages/brew.1
Labels: bug

#823 test: Work around test failure on CircleCI macOS
  Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Labels: bug

#824 LinkageChecker: Add libanl.so.1 to the whitelist [Linux]
  Library/Homebrew/linkage_checker.rb
Labels: bug

#825 JavaRequirement: Search in jdk jdk@8 jdk@7 [Linux]
  Library/Homebrew/extend/os/linux/requirements/java_requirement.rb
  Library/Homebrew/requirements/java_requirement.rb
Labels: enhancement

#826 shims/linux/super/make: use command -v
  Library/Homebrew/shims/linux/super/make
Labels: enhancement

#833 LinkageChecker: Add libmvec.so.1 to the white list [Linux]
  Library/Homebrew/linkage_checker.rb
Labels: bug
